### ISSUE TITLE
NameError: name 'G' is not defined

### ISSUE THREAD

**Issue by subwaystation** [anialisiecka/ALIBI#3]
```
bash alibi.sh -i ~/Downloads/hogwild\_paper/1D/DRB1-3123.fa.gz.seqwish.gfa 
Traceback (most recent call last):
  File "/home/heumos/git/ALIBI/./src/sort.py", line 123, in \<module>
    main()
  File "/home/heumos/git/ALIBI/./src/sort.py", line 120, in main
    linSort(infile)
  File "/home/heumos/git/ALIBI/./src/sort.py", line 110, in linSort
    addEdgeBetweenComponents(e, blocks)
  File "/home/heumos/git/ALIBI/./src/sort.py", line 54, in addEdgeBetweenComponents
    for u in G.graph\[e\[0\]\]:
NameError: name 'G' is not defined
```

It seems https://github.com/anialisiecka/ALIBI/commit/34c4aa4339ffbe6fbe99916407939ff575dddbd5 has broken ALIBI. This can easily be fixed by adding the graph `G` as an argument to `addEdgeBetweenComponents`. Thanks!

**Comment by anialisiecka** [comment]
I just fixed the code. 

Thank you

**Comment by subwaystation** [comment]
Thank you for the quick fix!
